// Do not edit. This file is machine generated by the Resource DLL Wizard.

library GroovyShoot;

{ITE} {DFMFileType} {AboutForm.dfm}
{ITE} {DFMFileType} {HelpForm.dfm}
{ITE} {DFMFileType} {ImageProcessForm.dfm}
{ITE} {DFMFileType} {MainForm.dfm}
{ITE} {DFMFileType} {SelectAreaForm.dfm}
{ITE} {RCFileType} {Win32\Release\GroovyShoot_DRC.rc}

{$R 'AboutForm.dfm' 'about_winForm:TForm'}
{$R 'HelpForm.dfm' 'help_winForm:TForm'}
{$R 'ImageProcessForm.dfm' 'process_winForm:TForm'}
{$R 'MainForm.dfm' 'main_winForm:TForm'}
{$R 'SelectAreaForm.dfm' 'selectArea_winForm:TForm'}
{$R 'Win32\Release\GroovyShoot_DRC.res' 'Win32\Release\GroovyShoot_DRC.rc'}

{$E ENU}

begin
end.
